### ISSUE TITLE
Handle headers as `string[]`

### ISSUE THREAD

**Issue by mydea** [gas-buddy/opentelemetry-instrumentation-fetch-node#14]
See: https://github.com/getsentry/sentry-javascript/issues/10936

It seems that Undici 6.7.0 has changed the signature of headers, this probably also needs to be addressed here I believe?

**Comment by dotansimha** [comment]
I also noticed that while upgrading a NodeJS version from `21.7.1` to `21.7.2`. This upgrade also includes an `undici` version upgrade (built-in in Node): https://github.com/nodejs/node/releases/tag/v21.7.2

The actual error is: 

```
TypeError: request.headers.push is not a function
    at processHeader (node:internal/deps/undici/undici:6451:25)
    at Request.addHeader (node:internal/deps/undici/undici:6380:9)
    at setHeadersOnRequest (file:///app/index.js:184989:12)
    at _onRequestCreate (file:///app/index.js:184893:9)
    at Channel.publish (node:diagnostics_channel:142:9)
    at new Request (node:internal/deps/undici/undici:6281:27)
    at [dispatch] (node:internal/deps/undici/undici:9060:25)
    at Intercept (node:internal/deps/undici/undici:8795:20)
    at [Intercepted Dispatch] (node:internal/deps/undici/undici:5659:16)
    at Client.dispatch (node:internal/deps/undici/undici:5675:44)
    at [dispatch] (node:internal/deps/undici/undici:5906:32)
    at [Intercepted Dispatch] (node:internal/deps/undici/undici:5652:33)
    at Pool.dispatch (node:internal/deps/undici/undici:5675:44)
    at [dispatch] (node:internal/deps/undici/undici:9488:27)
    at Intercept (node:internal/deps/undici/undici:8795:20)
    at [Intercepted Dispatch] (node:internal/deps/undici/undici:5659:16)
```

**Comment by dotansimha** [comment]
@mydea @djMax any idea where the exact piece of code that needs to be adjusted? and how to keep it backward compatible? I can send a PR if that helps. Thanks!

**Comment by djMax** [comment]
So I know that this module is being "redone" in the core opentelemetry SDKs, but let me give a look and see if it's easy.

**Comment by djMax** [comment]
I don't even see anything in this instrumentation the SETS headers, so I don't see how this causes the problem (but still looking). Is there a simple repro I can try?

**Comment by djMax** [comment]
Ok, I found it. New version will publish any minute now that hopefully fixes it, please test and let me know.

**Comment by dotansimha** [comment]
1.2.0 seems to fix the issue, thank you!
